### ISSUE TITLE
Allow multiple reference RPCs

### ISSUE THREAD

**Issue by agouin** [strangelove-ventures/half-life#21]
@agouin Just wanted to ask a thing since this is suggestion issue, and you're the best person for this, 

Adding support for multiple RPC urls and pick the healthy one by monitor. It should give tolerance. I'm having problem of this in some chains where some public RPCs are facing latency and that leads to problem `error fetching block xxx from rpc server`

Before
```yaml
...
validators:
- name: Osmosis
  rpc: (string)http://SOME_OSMOSIS_RPC_SERVER:26657
...
```

After

```yaml
...
validators:
- name: Osmosis
  rpcs: (array)
  - http://SOME_OSMOSIS_RPC_SERVER1:26657
  - http://SOME_OSMOSIS_RPC_SERVER2:26657
  - http://SOME_OSMOSIS_RPC_SERVER3:26657
...
```

I think I can try to integrate this using [strangelove-ventures/lens](https://github.com/strangelove-ventures/lens)

_Originally posted by @pratikbin in https://github.com/strangelove-ventures/half-life/issues/7#issuecomment-1301724823_
