### ISSUE TITLE
few suggestions

### ISSUE THREAD

**Issue by satman81** [strangelove-ventures/half-life#7]
- [ ] right now it seems sentry nodes only run on grpc, it would be great to configure rpc based nodes as well.
- [x] sometimes node is not a validator, in that case an option to disable signing block option would be great
- [x] when sentry nodes are not available in that case an option to check incremental block height and if they don't increase then send alert

**Comment by agouin** [comment]
In `v0.1.9`, you can now provide `fullnode: true` for a config entry and it will not check signed blocks. It will only monitor reachable and in sync for the sentries that case.

**Comment by agouin** [comment]
An alert will be generated if any sentry is more than 5 blocks behind the reference RPC

**Comment by satman81** [comment]
Awesome thanks.

Can we configure RPC based sentry nodes, besides gRPC?

**Comment by pratikbin** [comment]
@agouin Just wanted to ask a thing since this is suggestion issue, and you're the best person for this, 

Adding support for multiple RPC urls and pick the healthy one by monitor. It should give tolerance. I'm having problem of this in some chains where some public RPCs are facing latency and that leads to problem `error fetching block xxx from rpc server`

Before
```yaml
...
validators:
- name: Osmosis
  rpc: (string)http://SOME_OSMOSIS_RPC_SERVER:26657
...
```

After

```yaml
...
validators:
- name: Osmosis
  rpcs: (array)
  - http://SOME_OSMOSIS_RPC_SERVER1:26657
  - http://SOME_OSMOSIS_RPC_SERVER2:26657
  - http://SOME_OSMOSIS_RPC_SERVER3:26657
...
```

I think I can try to integrate that using [strangelove-ventures/lens](https://github.com/strangelove-ventures/lens)
